# Generated by Django 6.0.4 on 2026-05-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
