# Generated by Django 6.0.4 on 2026-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_buyer_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='seventwel',
        ),
        migrations.AddField(
            model_name='buyer',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='business_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='buyer/documents/gst/'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='msme_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='trade_license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='trade_license_doc',
            field=models.FileField(blank=True, null=True, upload_to='buyer/documents/trade_license/'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
