# Generated by Django 6.0.4 on 2026-05-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_chatroom_all_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'Ai')], max_length=10)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='chat/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='chat/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='farmer.chatroom')),
            ],
        ),
        migrations.DeleteModel(
            name='all_messages',
        ),
    ]
