# Generated by Django 6.0.4 on 2026-05-21 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_message_delete_all_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='bloag/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='bloag/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
