# Generated by Django 6.0.4 on 2026-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('grain cereals', 'Grain cereals'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('pulses', 'Pulses'), ('spices', 'Spices'), ('cotton', 'Cotton')], max_length=20),
        ),
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
