# Generated by Django 6.0.4 on 2026-05-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_crop_is_approved_alter_crop_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='acres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
