# Generated by Django 6.0.4 on 2026-06-04 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_farmer_acres'),
    ]

    operations = [
        migrations.CreateModel(
            name='community_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='community/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_my', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
