# Generated by Django 6.0.4 on 2026-06-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_community_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
