# Generated by Django 6.0.4 on 2026-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_farmer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
