# Generated by Django 6.0.4 on 2026-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0014_gov_info_delete_gove_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='gov_info',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
