# Generated by Django 6.0.4 on 2026-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0017_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
