# Generated by Django 6.0.4 on 2026-06-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0019_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='breaking_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
