# Generated by Django 6.0.4 on 2026-06-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0020_news_breaking_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
