# Generated by Django 6.0.3 on 2026-07-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0021_delete_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scheduled_deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
