# Generated by Django 6.0.3 on 2026-07-17 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0022_user_scheduled_deletion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tractor', 'Tractor'), ('harvester', 'Harvester'), ('other', 'Other Machinery'), ('tools', 'Machinery Tools'), ('hand', 'Hand Tools')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='farmer_tools/images/')),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented Out'), ('sold', 'Sold')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('original_price', models.PositiveIntegerField(help_text='Original purchase price (used for auto price estimation)')),
                ('years_used', models.PositiveIntegerField(default=0, help_text='Number of years the tool has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_tools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
