# Generated by Django 6.0.3 on 2026-07-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0023_farmer_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmertool',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
