# Generated by Django 6.0.3 on 2026-07-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0024_alter_farmertool_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmertool',
            name='predicted_price',
            field=models.PositiveIntegerField(blank=True, help_text='AI Predicted price at the time of listing', null=True),
        ),
    ]
