# Generated by Django 6.0.3 on 2026-07-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0025_farmertool_predicted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='notif_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='notif_gov_schemes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='notif_new_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='notif_price_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='notif_sms',
            field=models.BooleanField(default=False),
        ),
    ]
