# Generated by Django 6.0.3 on 2026-07-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0026_farmer_notif_blog_farmer_notif_gov_schemes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='doc_edit_permission',
            field=models.BooleanField(default=False, help_text='Allow farmer to edit documents after initial upload'),
        ),
    ]
