# Generated by Django 6.0.4 on 2026-07-21 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0027_farmer_doc_edit_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_premium_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_price', models.IntegerField(blank=True, default=99, null=True)),
                ('premium_price', models.IntegerField(blank=True, default=199, null=True)),
                ('year_dis', models.IntegerField(blank=True, default=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_selling_limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.IntegerField(blank=True, default=2.5, null=True)),
                ('total_sell_kg', models.IntegerField(blank=True, default=0, null=True)),
                ('sellilimit', models.IntegerField(blank=True, default=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='premium_buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_type', models.CharField(choices=[('Free', 'Free'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20)),
                ('premium_time', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Premium_user', to='farmer.farmer')),
            ],
        ),
    ]
