# Generated by Django 6.0.3 on 2026-07-22 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0028_farmer_premium_plans_farmer_selling_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_premium_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('coupon_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_farmer_history', to='farmer.farmer')),
            ],
        ),
    ]
