# Generated by Django 6.0.4 on 2026-06-22 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('msme_no', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_license', models.CharField(blank=True, max_length=50, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='buyer/documents/gst/')),
                ('trade_license_doc', models.FileField(blank=True, null=True, upload_to='buyer/documents/trade_license/')),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('adharno', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('adharcard', models.FileField(blank=True, null=True, upload_to='buyer/documents/adharcard/')),
                ('pancard', models.FileField(blank=True, null=True, upload_to='buyer/documents/pancard/')),
                ('passbook', models.FileField(blank=True, null=True, upload_to='buyer/documents/passbook/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='buyer/profile_photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
