# Generated by Django 6.0.4 on 2026-06-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='adharcard',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='adharno',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='msme_no',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='pancard',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='passbook',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='trade_license',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='trade_license_doc',
        ),
        migrations.AddField(
            model_name='buyer',
            name='enable_update',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pancard', models.FileField(blank=True, null=True, upload_to='buyer/documents/pancard/')),
                ('passbook', models.FileField(blank=True, null=True, upload_to='buyer/documents/passbook/')),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_bank', to='buyer.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='verification_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='buyer/profile_photos/')),
                ('msme_no', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_license', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_license_doc', models.FileField(blank=True, null=True, upload_to='buyer/documents/trade_license/')),
                ('adharno', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('adharcard', models.FileField(blank=True, null=True, upload_to='buyer/documents/adharcard/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_details', to='buyer.buyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
