# Generated by Django 6.0.4 on 2026-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_buyer_pincode_buyer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
