# Generated by Django 6.0.3 on 2026-06-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_cart_final_price_cart_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
        migrations.AddField(
            model_name='cart',
            name='tax_per',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
