# Generated by Django 6.0.4 on 2026-06-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Order', 'Order'), ('Payment', 'Payment'), ('Bulk', 'Bulk'), ('Export', 'Export')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='buyer.buyer')),
            ],
        ),
    ]
