# Generated by Django 6.0.4 on 2026-06-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('Order', 'Order'), ('Payment', 'Payment'), ('Bulk', 'Bulk'), ('Export', 'Export'), ('Kyc', 'Kyc')], max_length=20),
        ),
    ]
