# Generated by Django 6.0.4 on 2026-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
