# Generated by Django 6.0.3 on 2026-06-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_premiume',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='premium_buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_type', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20)),
                ('premium_time', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Premium_user', to='buyer.buyer')),
            ],
        ),
    ]
