# Generated by Django 6.0.3 on 2026-06-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_buyer_is_premiume_premium_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='premium_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_price', models.IntegerField(blank=True, default=99, null=True)),
                ('premium_price', models.IntegerField(blank=True, default=199, null=True)),
                ('year_dis', models.IntegerField(blank=True, default=20, null=True)),
            ],
        ),
    ]
