# Generated by Django 6.0.3 on 2026-07-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_premium_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
