# Generated by Django 6.0.4 on 2026-07-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0014_cart_total_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_limit',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
