# Generated by Django 6.0.4 on 2026-07-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0015_cart_cart_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium_buyer',
            name='premium_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20),
        ),
    ]
