# Generated by Django 6.0.4 on 2026-07-02 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0016_alter_premium_buyer_premium_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium_buyer',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
