# Generated by Django 6.0.4 on 2026-07-04 10:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0017_alter_premium_buyer_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='premium_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('coupon_code', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_buyer_history', to='buyer.buyer')),
            ],
        ),
    ]
