# Generated by Django 6.0.3 on 2026-07-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0019_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon',
            new_name='premium_coupon',
        ),
    ]
