# Generated by Django 6.0.4 on 2026-07-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0020_rename_coupon_premium_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('Order', 'Order'), ('Payment', 'Payment'), ('Bulk', 'Bulk'), ('Export', 'Export'), ('Kyc', 'Kyc'), ('Premium', 'Premium')], max_length=20),
        ),
    ]
