# Generated by Django 6.0.4 on 2026-07-11 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0021_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulkrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('required_quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('required_date', models.DateField()),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_district', models.CharField(max_length=100)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_procurement_requests', to='buyer.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='exportinquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('crop_name', models.CharField(max_length=200)),
                ('required_quantity', models.PositiveIntegerField(help_text='Quantity in KG')),
                ('packaging_type', models.CharField(max_length=100)),
                ('quality_standard', models.CharField(max_length=100)),
                ('shipping_port', models.CharField(max_length=150)),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_delivery', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_inquiries', to='buyer.buyer')),
            ],
        ),
    ]
