# Generated by Django 6.0.3 on 2026-07-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0022_bulkrequest_exportinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='update_request',
            field=models.BooleanField(default=False),
        ),
    ]
